language: go

go:
  - 1.12.x
  - 1.13.x

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.1

script: 
  - test -z "$(go fmt ./...)"
  - go vet ./...
  - go test -v --race -tags unit ./...
  - go build -o main .
  - golangci-lint run --enable-all ./...