// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type None struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *None) Reset()         { *m = None{} }
func (m *None) String() string { return proto.CompactTextString(m) }
func (*None) ProtoMessage()    {}
func (*None) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *None) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_None.Unmarshal(m, b)
}
func (m *None) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_None.Marshal(b, m, deterministic)
}
func (m *None) XXX_Merge(src proto.Message) {
	xxx_messageInfo_None.Merge(m, src)
}
func (m *None) XXX_Size() int {
	return xxx_messageInfo_None.Size(m)
}
func (m *None) XXX_DiscardUnknown() {
	xxx_messageInfo_None.DiscardUnknown(m)
}

var xxx_messageInfo_None proto.InternalMessageInfo

type AuthRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuthRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type IPRequest struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IPRequest) Reset()         { *m = IPRequest{} }
func (m *IPRequest) String() string { return proto.CompactTextString(m) }
func (*IPRequest) ProtoMessage()    {}
func (*IPRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *IPRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPRequest.Unmarshal(m, b)
}
func (m *IPRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPRequest.Marshal(b, m, deterministic)
}
func (m *IPRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPRequest.Merge(m, src)
}
func (m *IPRequest) XXX_Size() int {
	return xxx_messageInfo_IPRequest.Size(m)
}
func (m *IPRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IPRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IPRequest proto.InternalMessageInfo

func (m *IPRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type BucketRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BucketRequest) Reset()         { *m = BucketRequest{} }
func (m *BucketRequest) String() string { return proto.CompactTextString(m) }
func (*BucketRequest) ProtoMessage()    {}
func (*BucketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *BucketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BucketRequest.Unmarshal(m, b)
}
func (m *BucketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BucketRequest.Marshal(b, m, deterministic)
}
func (m *BucketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BucketRequest.Merge(m, src)
}
func (m *BucketRequest) XXX_Size() int {
	return xxx_messageInfo_BucketRequest.Size(m)
}
func (m *BucketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BucketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BucketRequest proto.InternalMessageInfo

func (m *BucketRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *BucketRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *BucketRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type OkResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OkResponse) Reset()         { *m = OkResponse{} }
func (m *OkResponse) String() string { return proto.CompactTextString(m) }
func (*OkResponse) ProtoMessage()    {}
func (*OkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *OkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OkResponse.Unmarshal(m, b)
}
func (m *OkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OkResponse.Marshal(b, m, deterministic)
}
func (m *OkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OkResponse.Merge(m, src)
}
func (m *OkResponse) XXX_Size() int {
	return xxx_messageInfo_OkResponse.Size(m)
}
func (m *OkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OkResponse proto.InternalMessageInfo

func (m *OkResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*None)(nil), "grpc.None")
	proto.RegisterType((*AuthRequest)(nil), "grpc.AuthRequest")
	proto.RegisterType((*IPRequest)(nil), "grpc.IPRequest")
	proto.RegisterType((*BucketRequest)(nil), "grpc.BucketRequest")
	proto.RegisterType((*OkResponse)(nil), "grpc.OkResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x14, 0x6c, 0x3e, 0x2c, 0xcd, 0x2b, 0x46, 0xdd, 0x7a, 0x08, 0xd1, 0x83, 0xe4, 0x24, 0x82, 0x51,
	0xd4, 0x3f, 0x90, 0x2a, 0x42, 0x41, 0xac, 0xe6, 0xe2, 0x39, 0x26, 0x8f, 0x76, 0x49, 0xcc, 0xae,
	0xd9, 0x0d, 0xfe, 0x09, 0x7f, 0xb4, 0x64, 0x97, 0x6e, 0x3f, 0x40, 0xc8, 0xa1, 0xc7, 0x9d, 0x79,
	0x33, 0xf3, 0x32, 0x2f, 0xe0, 0x65, 0x9c, 0xc6, 0xbc, 0x61, 0x92, 0x11, 0x77, 0xd1, 0xf0, 0x3c,
	0x1a, 0x82, 0xfb, 0xca, 0x6a, 0x8c, 0xe6, 0x30, 0x4e, 0x5a, 0xb9, 0x4c, 0xf1, 0xbb, 0x45, 0x21,
	0xc9, 0x29, 0x1c, 0x54, 0x6c, 0x41, 0xeb, 0xc0, 0xba, 0xb0, 0x2e, 0xbd, 0x54, 0x3f, 0x48, 0x08,
	0x23, 0x9e, 0x09, 0xf1, 0xc3, 0x9a, 0x22, 0xb0, 0x15, 0x61, 0xde, 0xc4, 0x07, 0x9b, 0xf2, 0xc0,
	0x51, 0xa8, 0x4d, 0x79, 0x74, 0x06, 0xde, 0xec, 0x6d, 0x65, 0xa7, 0x49, 0xcb, 0x90, 0xef, 0x70,
	0x38, 0x6d, 0xf3, 0x12, 0xe5, 0xfe, 0xf2, 0xce, 0x01, 0xe6, 0x65, 0x8a, 0x82, 0xb3, 0x5a, 0x60,
	0xc7, 0xb2, 0x52, 0x99, 0x8d, 0x52, 0x9b, 0x95, 0x77, 0xbf, 0x0e, 0x38, 0x09, 0xa7, 0xe4, 0x06,
	0xfc, 0xa4, 0x28, 0x66, 0xf5, 0xb4, 0xca, 0xf2, 0xf2, 0x85, 0x0a, 0x49, 0x8e, 0xe2, 0xae, 0x87,
	0xd8, 0xec, 0x1a, 0x82, 0x06, 0x54, 0x2b, 0x03, 0x23, 0xf8, 0x58, 0x52, 0x89, 0x7d, 0x04, 0x0f,
	0x30, 0x79, 0xc2, 0x0a, 0x25, 0x3e, 0x37, 0xec, 0xab, 0x77, 0xcc, 0x96, 0xaa, 0x77, 0xd6, 0x2d,
	0x8c, 0x1f, 0x2b, 0xcc, 0x1a, 0xdd, 0x25, 0x99, 0x68, 0x72, 0xab, 0xd9, 0x1d, 0xc5, 0x35, 0xb8,
	0xdd, 0x99, 0xc9, 0x89, 0x46, 0x37, 0x4e, 0x1e, 0x1e, 0x6b, 0x68, 0x5d, 0x62, 0x34, 0x20, 0x57,
	0xe0, 0xeb, 0x00, 0xf3, 0x1d, 0x1b, 0x76, 0x3b, 0xd6, 0xab, 0xd9, 0xf5, 0xf6, 0xff, 0xce, 0x7e,
	0x0e, 0xd5, 0x2f, 0x78, 0xff, 0x17, 0x00, 0x00, 0xff, 0xff, 0x61, 0x01, 0x87, 0xa3, 0x8f, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApiClient interface {
	AddInBlackList(ctx context.Context, in *IPRequest, opts ...grpc.CallOption) (*None, error)
	AddInWhiteList(ctx context.Context, in *IPRequest, opts ...grpc.CallOption) (*None, error)
	DeleteFromBlackList(ctx context.Context, in *IPRequest, opts ...grpc.CallOption) (*None, error)
	DeleteFromWhiteList(ctx context.Context, in *IPRequest, opts ...grpc.CallOption) (*None, error)
	ClearBucket(ctx context.Context, in *BucketRequest, opts ...grpc.CallOption) (*None, error)
	Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*OkResponse, error)
	// For integration tests when need clean lists before run tests
	ClearBlackList(ctx context.Context, in *None, opts ...grpc.CallOption) (*None, error)
	ClearWhiteList(ctx context.Context, in *None, opts ...grpc.CallOption) (*None, error)
}

type apiClient struct {
	cc *grpc.ClientConn
}

func NewApiClient(cc *grpc.ClientConn) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) AddInBlackList(ctx context.Context, in *IPRequest, opts ...grpc.CallOption) (*None, error) {
	out := new(None)
	err := c.cc.Invoke(ctx, "/grpc.Api/AddInBlackList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) AddInWhiteList(ctx context.Context, in *IPRequest, opts ...grpc.CallOption) (*None, error) {
	out := new(None)
	err := c.cc.Invoke(ctx, "/grpc.Api/AddInWhiteList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) DeleteFromBlackList(ctx context.Context, in *IPRequest, opts ...grpc.CallOption) (*None, error) {
	out := new(None)
	err := c.cc.Invoke(ctx, "/grpc.Api/DeleteFromBlackList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) DeleteFromWhiteList(ctx context.Context, in *IPRequest, opts ...grpc.CallOption) (*None, error) {
	out := new(None)
	err := c.cc.Invoke(ctx, "/grpc.Api/DeleteFromWhiteList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) ClearBucket(ctx context.Context, in *BucketRequest, opts ...grpc.CallOption) (*None, error) {
	out := new(None)
	err := c.cc.Invoke(ctx, "/grpc.Api/ClearBucket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*OkResponse, error) {
	out := new(OkResponse)
	err := c.cc.Invoke(ctx, "/grpc.Api/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) ClearBlackList(ctx context.Context, in *None, opts ...grpc.CallOption) (*None, error) {
	out := new(None)
	err := c.cc.Invoke(ctx, "/grpc.Api/ClearBlackList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) ClearWhiteList(ctx context.Context, in *None, opts ...grpc.CallOption) (*None, error) {
	out := new(None)
	err := c.cc.Invoke(ctx, "/grpc.Api/ClearWhiteList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServer is the server API for Api service.
type ApiServer interface {
	AddInBlackList(context.Context, *IPRequest) (*None, error)
	AddInWhiteList(context.Context, *IPRequest) (*None, error)
	DeleteFromBlackList(context.Context, *IPRequest) (*None, error)
	DeleteFromWhiteList(context.Context, *IPRequest) (*None, error)
	ClearBucket(context.Context, *BucketRequest) (*None, error)
	Auth(context.Context, *AuthRequest) (*OkResponse, error)
	// For integration tests when need clean lists before run tests
	ClearBlackList(context.Context, *None) (*None, error)
	ClearWhiteList(context.Context, *None) (*None, error)
}

// UnimplementedApiServer can be embedded to have forward compatible implementations.
type UnimplementedApiServer struct {
}

func (*UnimplementedApiServer) AddInBlackList(ctx context.Context, req *IPRequest) (*None, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddInBlackList not implemented")
}
func (*UnimplementedApiServer) AddInWhiteList(ctx context.Context, req *IPRequest) (*None, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddInWhiteList not implemented")
}
func (*UnimplementedApiServer) DeleteFromBlackList(ctx context.Context, req *IPRequest) (*None, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFromBlackList not implemented")
}
func (*UnimplementedApiServer) DeleteFromWhiteList(ctx context.Context, req *IPRequest) (*None, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFromWhiteList not implemented")
}
func (*UnimplementedApiServer) ClearBucket(ctx context.Context, req *BucketRequest) (*None, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearBucket not implemented")
}
func (*UnimplementedApiServer) Auth(ctx context.Context, req *AuthRequest) (*OkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auth not implemented")
}
func (*UnimplementedApiServer) ClearBlackList(ctx context.Context, req *None) (*None, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearBlackList not implemented")
}
func (*UnimplementedApiServer) ClearWhiteList(ctx context.Context, req *None) (*None, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearWhiteList not implemented")
}

func RegisterApiServer(s *grpc.Server, srv ApiServer) {
	s.RegisterService(&_Api_serviceDesc, srv)
}

func _Api_AddInBlackList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).AddInBlackList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Api/AddInBlackList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).AddInBlackList(ctx, req.(*IPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_AddInWhiteList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).AddInWhiteList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Api/AddInWhiteList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).AddInWhiteList(ctx, req.(*IPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_DeleteFromBlackList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).DeleteFromBlackList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Api/DeleteFromBlackList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).DeleteFromBlackList(ctx, req.(*IPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_DeleteFromWhiteList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).DeleteFromWhiteList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Api/DeleteFromWhiteList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).DeleteFromWhiteList(ctx, req.(*IPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_ClearBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).ClearBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Api/ClearBucket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).ClearBucket(ctx, req.(*BucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Api/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Auth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_ClearBlackList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(None)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).ClearBlackList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Api/ClearBlackList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).ClearBlackList(ctx, req.(*None))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_ClearWhiteList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(None)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).ClearWhiteList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Api/ClearWhiteList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).ClearWhiteList(ctx, req.(*None))
	}
	return interceptor(ctx, in, info, handler)
}

var _Api_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddInBlackList",
			Handler:    _Api_AddInBlackList_Handler,
		},
		{
			MethodName: "AddInWhiteList",
			Handler:    _Api_AddInWhiteList_Handler,
		},
		{
			MethodName: "DeleteFromBlackList",
			Handler:    _Api_DeleteFromBlackList_Handler,
		},
		{
			MethodName: "DeleteFromWhiteList",
			Handler:    _Api_DeleteFromWhiteList_Handler,
		},
		{
			MethodName: "ClearBucket",
			Handler:    _Api_ClearBucket_Handler,
		},
		{
			MethodName: "Auth",
			Handler:    _Api_Auth_Handler,
		},
		{
			MethodName: "ClearBlackList",
			Handler:    _Api_ClearBlackList_Handler,
		},
		{
			MethodName: "ClearWhiteList",
			Handler:    _Api_ClearWhiteList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
