# limits in minutes for each login/password/ip
limits:
  login: 10
  password: 100
  ip: 1000

timeouts:
  bucket_active: "2m"

logger:
  level: "debug"
  output_paths:
    - stderr
    - /tmp/antibruteforce/outlog
  error_output_paths:
    - stderr
    - /tmp/antibruteforce/errlog
